### PR TITLE
Improved c kc stop command

### PR DESCRIPTION
**Pull request by smebberson**
Added a `<location>` option to `c kc stop`.

## Setup

- [x] Pull down this PR.
- [x] Execute `yarn link`.
- [x] In a project you want to test it with execute `yarn link @idearium/cli`.

## Testing

- [x] Execute `c kc` to ensure the stop command exists.
- [x] Execute `c kc stop --help` to ensure the documentation is accurate.
- [x] Execute `c kc stop <location>` and make sure just that Kubernetes object is stopped.

### CODE REVIEW

**Comment by allanchau** [comment]
@smebberson I've been running with this lately `.then(() => exec('c kc clean all'))`. Do you think it would be worth adding something similar to this pr?

**Comment by smebberson** [comment]
@allanchau, regarding your comment, what did you have in mind?

**Comment by allanchau** [comment]
@smebberson I was thinking it should probably be smart enough to use the location as well.
`c kc stop` would clean all locations, but `c kc stop app` would only clean the `app location`.

**Comment by smebberson** [comment]
@allanchau, that's how it works?!

**Comment by smebberson** [comment]
Oh. Right. I get you now. You want to clean it as well after stop. I think we should think about that in another PR. Because perhaps `c kc build -d app` should clean too?

**Pull request merged**
