### PR TITLE
set mongo version

### PR DESCRIPTION
**Pull request by allanchau**
This PR locks down the mongo version.

**Testing**

- [ ] Test a mongo command `c mongo sync production` etc.

### CODE REVIEW

**Comment by smebberson** [comment]
@allanchau, I've just realised, I made #22 which requires Mongo 3.4. Why do we need this version in particular?

**Comment by allanchau** [comment]
@smebberson I chose 3.2 because it matches our current compose version. It should probably be 3.4 or 3.6 with the move to IBM cloud though.

**Comment by smebberson** [comment]
@allanchau, why do we need this PR though? Can we just continue with `latest`? Does it solve a problem you had or?

**Comment by allanchau** [comment]
The problem with what we had is commands may be different between the latest mongo shell and what is on production. Mongo is frequently updated too so I often see Docker downloading a new image which can take a while on slower connections.

**Comment by smebberson** [comment]
@allanchau, looks like there are conflicts?

**Comment by allanchau** [comment]
@smebberson Yeah fixing them up now

**Pull request merged**
