### PR TITLE
Mongo connect arguments

### PR DESCRIPTION
**Pull request by smebberson**
This PR adds support for more flexible `c.js` MongoDB related definitions, allowing the arguments to be defined that will be passed directly to the `mongo` command. This is to support IBM Cloud database connections.

**Please note:** These changes are not backwards compatible and require a change to `c.js` MongoDB definitions. Suggested next version is `v3.0.0`.

## Setup

- [x] Pull down this PR.
- [x] Execute `yarn link`.
- [x] Go into a project and execute `c mongo download --help`, you should see a reference to `<collection>`.

## Related PRs

- idearium/teamly#620

## Testing

- [x] Execute `c mongo sync production` to sync a production database, make sure all collections come across.
- [x] Execute `c mongo sync production <collection>`, make sure only one collection comes across.
- [x] Execute `c mongo sync beta` to sync a beta database, make sure all collections come across.
- [x] Execute `c mongo sync beta <collection>`, make sure only one collection comes across.
- [x] Execute `c mongo download production` to download a production database, make sure all collections come across.
- [x] Execute `c mongo download production <collection>`, make sure only one collection comes across.
- [x] Execute `c mongo download beta` to download a beta database, make sure all collections come across.
- [x] Execute `c mongo download beta <collection>`, make sure only one collection comes across.
- [x] Execute `c mongo import production` to import the production database, make sure all collections are imported.
- [x] Execute `c mongo import production <collection>`, make sure only one collection is imported.
- [x] Execute `c mongo connect local` to ensure a local database connection works.
- [x] Execute `c mongo connect beta` to ensure a beta database connection works.
- [x] Execute `c mongo connect production` to ensure a production database connection works.

### CODE REVIEW

**Comment by smebberson** [comment]
@allanchau, shit, yeah, I meant to do that. Done now :)

**Comment by DinoLeung** [comment]
@smebberson I'm having difficulties connecting to local db with this cli

**Comment by smebberson** [comment]
@DinoLeung, got more info? @allanchau, did you have any issues?

**Comment by allanchau** [comment]
@smebberson @DinoLeung Just the mongo version, without it nsinclude didn't work.

I could connect to everything, @DinoLeung is your Idearium infrastructure running?

**Comment by DinoLeung** [comment]
so I updated the cli version to `idearium/cli#0722a31772ce2fe348862a9c15084bfe15e30049`, then did a `yarn install` in a fresh terminal. And I got the following error. 
And yes infrastructure is running good, I can connect DB with cliversion `2.1.3`
```
beta-on-ibm ✗ (local) ~/Developer/teamly $ c mongo connect local
MongoDB shell version v4.0.3
connecting to: mongodb://db.common.idearium.local:27017/tly
2019-05-07T05:42:58.693+0000 E QUERY    [js] Error: couldn't connect to server db.common.idearium.local:27017, connection attempt failed: SocketException: short read :
connect@src/mongo/shell/mongo.js:257:13
@(connect):1:6
exception: connect failed
```

**Comment by DinoLeung** [comment]
Ahh, never mind, this is to do with `c.js` in another project

**Pull request merged**
