### PR TITLE
Fixes mongo commands where database names differ

### PR DESCRIPTION
**Pull request by smebberson**
The previous mongo command updates didn't work properly when the database names were different. This resolves those issues.

## Setup

- [x] A list of steps to get started with testing.

## Verification and testing

- [x] Use `focusbooster-hq` for testing this project.
- [x] Pull down the previous version (i.e. `v3.0.0`, `master`).
- [x] Execute `yarn link` so you can use the code anywhere.
- [x] Execute `c mongo sync production fbusers`.
- [x] Verify it synchronised the data into the `fb-hq-production` database locally.
- [x] Pull down this branch.
- [x] Execute `c mongo sync production fbusers`.
- [x] Verify it synchronised the data into the `focusbooster-hq` database locally.

### CODE REVIEW

**Comment by allanchau** [comment]
@smebberson It works, but how do I verify `mongo command updates didn't work properly when the database names were different` has been fixed? I just tried to enter the wrong name and both branches gave me this
```shell
(local) $ c mongo sync production fbuserqwe
2019-05-27T22:47:28.655+0000    Failed: error connecting to db server: no reachable servers
2019-05-27T22:47:32.357+0000    preparing collections to restore from
2019-05-27T22:47:32.429+0000    done
(local) $ c mongo sync production fbuserqwe
2019-05-27T22:47:44.818+0000    Failed: error connecting to db server: no reachable servers
2019-05-27T22:47:48.271+0000    preparing collections to restore from
2019-05-27T22:47:48.317+0000    done
```

**Comment by smebberson** [comment]
@allanchau, you'll need to update the format to be the new format:

```
production: {
    host: 'host:port',
    name: 'name',
    params: [
        '--ssl',
        '--sslAllowInvalidCertificates',
    ],
    password: 'password',
    user: 'user',
}
```


Also, the steps above show you how to validate, synching the data into the `fb-hq-production` database locally, is incorrect - it should never have done that.

Why are the steps all ticked if it didn't work?

**Comment by allanchau** [comment]
@smebberson It did work when the collection name was correct

**Comment by smebberson** [comment]
@allanchau, I think it actually didn't connect to the remote database. If you see the logs, you'll probably see the same error.

**Pull request merged**
